### ISSUE TITLE
SynTexDunamicPlatform warning in logging

### ISSUE THREAD

**Issue by Hari-Seldon-nl** [SynTexDZN/homebridge-syntex#5]
Error message concerning SynTexDynamicPlatform. Plugin deleted as is is not anymore in your repository and can't find any info on it. Although after deletion there is still a warning in the log. 

"No plugin was found for the platform "SynTexDynamicPlatform" in your config.json. Please make sure the corresponding plugin is installed correctly." 

If Installation is required, please also provide info about possible/required entries in  Config.json

**_SORRY, was caused by remaining part in CONFIG. So no issue._**

**Comment by SynTexDZN** [comment]
Some explanation for you and others:

The SynTexDynamicPlatform is only a module and not a standalone plugin so it comes with the dependencies (when installing via NPM). It is only ment to be the basic framework for all of my plugins.

I also made several changes to the README file for more clearness so you should check it out especially if you wan't to upgrade to v5.3.0 (with English language support and much more).

~ **SynTex**
