### ISSUE TITLE
Plugin Crash after update to Node.js version (v14.17.0) and NPM v14.17.0 

### ISSUE THREAD

**Issue by Hari-Seldon-nl** [SynTexDZN/homebridge-syntex#6]
After installing the new Node.js version (v14.17.0) and NPM v14.17.0 on my iMac, the Syntex plugin crashes. 

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received type boolean (true)
    at Object.readdirSync (fs.js:1038:10)
    at new LanguageManager (/usr/local/lib/node_modules/homebridge-syntex/node_modules/syntex-webserver/language_manager.js:9:12)
    at new WebServer (/usr/local/lib/node_modules/homebridge-syntex/node_modules/syntex-webserver/main.js:13:21)
    at new SynTexPlatform (/usr/local/lib/node_modules/homebridge-syntex/index.js:23:20)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)`

**Comment by SynTexDZN** [comment]
Hey,
this problem could be caused by your config.json or a mistake of mine. Could you please share your config and the plugin version with us so we can help you?

~ **SynTex**

**Comment by Hari-Seldon-nl** [comment]
I just updated to the new homebridge-syntex v5.3.0 version. But no change. This error is new since Node.js version (v14.17.0) and NPM v14.17.0 on my iMac, which is my test environment. My 'real' HomeBridge (production) is my Raspberry PI 3b, which is still function well with the old Node.js and NPM.

        {
            "platform": "SynTex",
            "cacheDirectory": "./SynTex/settings",
            "logDirectory": "./SynTex/log",
            "port": 1711,
            "language": "us",
            "debug": false
        },
        {
            "platform": "SynTexWebHooks",
            "port": 1710,
            "language": "us",
            "logDirectory": "./SynTex/log",
            "cacheDirectory": "./SynTex/settings",
            "automationDirectory": "./SynTex/automation",
            "debug": false,
            "accessories": [
                {
                    "id": "XAN_ID_20",
                    "name": "Buitenkamer hoofd",
                    "services": {
                        "type": "led",
                        "requests": [
                            {
                                "trigger": "on",
                                "method": "GET",
                                "url": "http://192.168.50.150/API/?device=20&cmd=on"
                            },
                            {
                                "trigger": "off",
                                "method": "GET",
                                "url": "http://192.168.50.150/API/?device=20&cmd=off"
                            }
                        ]
                    }
                }
            ]
        },

**Comment by SynTexDZN** [comment]
You could try using absolute paths instead of relative ones. I had different problems with them in the past too. I also would recommend you to add the `automationDirectory` parameter to the `SynTex` platform ( *I forgot it in my example config* ) if you want to create some. I hope it works :D

~ **SynTex**
