### ISSUE TITLE
No longer responding to HTTP requests

### ISSUE THREAD

**Issue by ultrathew** [SynTexDZN/homebridge-syntex#7]
**Describe the bug**
HTTP requests no longer are registered by plugin or producing a response.

**Expected behavior**
HTTP post event should update value.

**Config**
Homebridge 1.5 on RPI, SynTex Webhooks v2.3.6

**Logs**
Nothing shown in logs.

**Comment by SynTexDZN** [comment]
Hey @ultrathew,
Let's check first if it is a config parameter issue. Could you please send the part of your 'config.json' that belongs to my plugins?

~ **SynTex**

**Comment by ultrathew** [comment]
Here you go, it's basically an outdoor sensor that sends its temperature and humidity readings this way:
http://[HOMEBRIDGEIP]:1710/devices?id=templeTemp&value=20

It's been working great until the most recent update.

`       {
            "platform": "SynTexWebHooks",
            "baseDirectory": "/var/lib/homebridge/SynTex",
            "port": 1710,
            "language": "us",
            "logDirectory": "./SynTex/log",
            "accessories": [
                {
                    "id": "templeRH",
                    "name": "Outdoor Humidity",
                    "services": "humidity"
                },
                {
                    "id": "templeTemp",
                    "name": "Outdoor Temperature",
                    "services": "temperature"
                }
            ]
        },`

**Comment by SynTexDZN** [comment]
The config for my plugins has changed since some recent updates. You have to update your config, too. Please read the README file to see what has changed.

~ **SynTex**
